name: Testing my Versioning Custom Action
on:
- push

jobs:
  get_test_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        uses: endybits/increment-version@v1.19
        with:
          type-versioning: 'minor'
      - id: version
        run: echo random-version ${{ steps.get-version.outputs.new-version}}
        shell: bash
      - id: default-version
        run: echo default-version ${{ steps.get-version.outputs.default-version}}
        shell: bash
