on: [push]

jobs:
  versioning_job:
    runs-on: ubuntu-latest
    name: A job to test versioning
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: versioning
        id: versioning_id
        uses: endybits/versioning@v0.6.3
        with:
          versioning-type: "major"
      # Use the output from the `versioning_id` step
      - name: Get version
        run: echo "The new version is ${{ steps.versioning_id.outputs.new_version}}"
